# https://taskfile.dev
# TODO check this
version: '3'

vars:
  allow: false

tasks:
  up:
    cmds:
      - docker-compose up
    dir: platform/compose
  down:
    cmds:
      - docker-compose down
    dir: platform/compose
